# -----------------------------
# Docker Compose for Kafka + Zookeeper + Notification Service
# -----------------------------

services:
  # -----------------------------
  # Zookeeper
  # -----------------------------
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  # -----------------------------
  # Kafka Broker
  # -----------------------------
  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    ports:
      - "9092:9092"

  # -----------------------------
  # Notification Service
  # -----------------------------
  notification-service:
    build: .                     # current folder (notification-service)
    container_name: notification-service
    depends_on:
      - kafka                     # Eureka remove कर दिया
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8087:8087"
